debug:
  flag: false
  mnemonic:  #Facilitates maintaining stable peerid during debugging
  teeTest: # The configuration here requires teeflag to be true to take effect.
    flag: false
    agent: # Tee encapsulation and verification proxy server address, mainly to facilitate debugging of tee functions
repo:
  disks: /opt/dcnetio/disks #"Repo location" mainly stores the official storage data of the DC platform
  ssd: /opt/dcnetio/data/dcstorage #"ssdRepo location,主要存放快速访问的相关数据" 
addrs:
  host: /ip4/0.0.0.0/tcp/4006/ip6/::/tcp/4006 #"Libp2p host bind address"  
  exMapPort:  #The external port configured for port mapping on the router
  announceAddr:  # "Libp2p announce address" is mainly used to tell the chain through which address the node can be accessed. If not configured, it will be obtained automatically.
  announceRelayAddr: false #Whether to use the relay address as the node address as well. This function can only be enabled when the network cannot be accessed by the external network due to special network configuration.
  excludeAddrs: #Node addresses submitted to the blockchain are not allowed, and some invalid addresses, such as loopback addresses and intranet addresses, are excluded to ensure the validity of addresses on the chain.
    - 127.0.0.1
    - 192.168.2
    - 192.168.0
  bootstrapAddresses:
  relayIpfsAddresses:
  chainUrl: ws://127.0.0.1:9944
teeFlag: true
dbrestore: true #Do you need to start the data recovery mode? In this mode, badgerdb.truncate is set to true. Some data may be deleted to restore the stored data.