chainNodeName: dcnet_neWPFMls
validatorFlag: ""  # "enable" or "disable"
chainSyncMode: full
chainWsUrl: ws://127.0.0.1:9944
chainRpcListenPort: 9944
pccsKey: 07ca6580ba9249569b15b1f7b1a34273
chainImage: ghcr.io/dcnetio/dcchain:0.1.4
nodeImage: ghcr.io/dcnetio/dcstorage:0.1.2
upgradeImage: ghcr.io/dcnetio/dcupgrade:0.1.7
pccsImage: ghcr.io/dcnetio/pccs:0.1.5
chainBootNode: "" 
chainExposeFlag: ""  # "enable" or "disable"
newVersion:
  mirrCids: